name: Configure SSH key
on: workflow_dispatch

env:
  home: C:\Users\administrator\.ssh #\.ssh\new_key_rsa
  keypathRsa: C:\Users\administrator\.ssh\new_key_rsa
  keypathEd: C:\Users\administrator\.ssh\new_key_ed
  script1: "ssh-keygen -t rsa -b 4096 -q -N \"\" -f C:\\Users\\Administrator\\.ssh\\new_key_rsa"
  pwsh: "C:\\Program Files\\PowerShell\\7\\pwsh.exe"
  password: ${{ secrets.PASSWORD }}

jobs:
  display-cred:
    #  create-and-display-ssh-key:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: secure password
        id: secpass
        shell: pwsh
        run: echo "password=$(ConvertTo-SecureString ${{ secrets.PASSWORD }} -AsPlainText -Force)" >> $env:GITHUB_OUTPUT
        
      - name: temp variables
        id: vars
        shell: pwsh
        run: |
          echo ${{ steps.secpass.outputs.password }}
          echo "cred=$(New-Object System.Management.Automation.PSCredential("tansatech\administrator", (ConvertTo-SecureString "Aime4274" -AsPlainText -Force)))" >> $env:GITHUB_OUTPUT
      
      - name: Install SSH Key
        run: |
          Start-Process -FilePath "powershell.exe" -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File ${{ env.script1  }}" -Credential ${{ steps.vars.outputs.cred }} -PassThru | Out-Null
        
