name: Configure SSH key
on: workflow_dispatch

env:
  home: C:\Users\administrator\.ssh #\.ssh\new_key_rsa
  keypathRsa: C:\Users\administrator\.ssh\new_key_rsa
  keypathEd: C:\Users\administrator\.ssh\new_key_ed
  script1: "ssh-keygen -t rsa -b 4096 -q -N \"\" -f C:\\Users\\Administrator\\.ssh\\new_key_rsa"
  pwrsh: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
  password: ${{ secrets.PASSWORD }}

jobs:
  display-red:
    #  create-and-display-ssh-key:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: temp variables
        id: vars
        shell: pwsh
        run: |
          echo "password=ConvertTo-SecureString ${{ secrets.PASSWORD }} -AsPlainText -Force" >> "$GITHUB_OUTPUT"
          echo "cred=New-Object -typename System.Management.Automation.PSCredential -argumentlist tansatech\administrator, ${{ env.password }}" >> "$GITHUB_OUTPUT"
        env:
            PSSWRD: ${{ steps.vars.outputs.password }}
            CRED: ${{ steps.vars.outputs.cred }}
            
      - name: setup env variable
        shell: pwsh
        run: |
          echo "env variable PSSWRD is ${{ env.PSSWRD }}"
          echo "env variable CRED is ${{ emv.CRED }}"
        
