name: Configure SSH key
on:
  workflow_dispatch

#env: 
#  keypathRsa: {{ $home  }}\.ssh\new_key_rsa
#  keypathEd: {{ $home  }}\.ssh\new_key_ed

jobs:
  display-home-dir: 
#  create-and-display-ssh-key:
    runs-on: [ self-hosted, Windows, X64 ]
    steps:
      - name: print home dir
        run: |
          Write-Host $home
          echo keypathRsa
          echo keypathEd
      
#      - name: Install SSH Key
#        run: |
#          ssh-keygen -t rsa -b 4096 -q -N "" -f ${{ env. keypathRsa }}
#          ssh-keygen -t ed25519 -N '""' -f ${{ env.keypathEd }}
  
  
