name: Configure SSH key
on:
  workflow_dispatch

env:
  home: $home
  keypathRsa: $home\.ssh\new_key_rsa
  keypathEd: $home\.ssh\new_key_ed

jobs:
  display-home-dir: 
#  create-and-display-ssh-key:
    runs-on: [ self-hosted, Windows, X64 ]
    steps:
      - name: print home dir
        run: |
          Write-Host ${{ env.home }}
          Write-Host ${{ env.keypathRsa }}
          Write-Host ${{ env.keypathEd }}
      
      - name: Install SSH Key
        run: |
         ssh-keygen -t rsa -b 4096 -q -N "" -f ${{ env. keypathRsa }}
         ssh-keygen -t ed25519 -N '""' -f ${{ env.keypathEd }}
         Write-Host ${{ env.keypathRsa }}
         Write-Host ${{ env.keypathEd }}
         Write-Host "The private rsa key is: \n" ${{ env.keypathRsa }}
         Write-Host "The public rsa key is: \n" ${{ env.keypathRsa }}.pub
         Write-Host "The private Ed key is: \n" ${{ env.keypathEd }}
         Write-Host "The public Ed key is: \n" ${{ env.keypathEd }}.pub
  
  
